package com.example.DataCompanyWeb.enums;

public enum CollaboratorFunction {
    ANALISTA, ARQUITETO_SOFTWARE, CIENTISTA_DADOS, DESENVOLVEDOR_BACKEND, DESENVOLVEDOR_FRONTEND,
    DESENVOLVEDOR_FULLSTACK, DESIGNER, ENGENHEIRO_QA, GERENTE_PROJETO, PRODUCT_OWNER, SCRUM_MASTER, UX_UI_DESIGNER
}
