package com.example.DataCompanyWeb.enums;

public enum ProjectArea {
    CIENCIA, CULTURA, EDUCACAO, ENTRETENIMENTO, FINANÇAS, INFRAESTRUTURA, POLITICA, SAUDE, SEGURANCA, TECNOLOGIA,
    TURISMO, UTILIDADES, VAREJO
}
